name: horda_client
description: Client SDK for Horda stateful serverless backend
version: 0.17.18
homepage: https://github.com/horda-ai/dart_client

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  horda_core: ^0.12.18
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  logging: ^1.2.0
  rxdart: ^0.27.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
